active_stack_id: 6ff9ea9a-9b83-4563-9d0a-87232d86ab2d
active_workspace_name: default
analytics_opt_in: true
store:
  api_token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxZmU5MjNjYy0xMmEwLTQxZDAtYWMzMC1iYTQxZTI4MDg2ZDkiLCJpc3MiOiJhZTRmMDgwZC1jMWMzLTQ3NzUtYWZkNi1jMTgyYTMzOWQxMDEiLCJhdWQiOiJhZTRmMDgwZC1jMWMzLTQ3NzUtYWZkNi1jMTgyYTMzOWQxMDEifQ.yjd6X-7DKCsZcr9-wjVr3G6USB_LG4VjzyBhX_Hg5Cw
  http_timeout: 30
  password: ''
  type: rest
  url: http://127.0.0.1:9000
  username: default
  verify_ssl: true
user_id: ae4f080d-c1c3-4775-afd6-c182a339d101
version: 0.58.2
