active_stack_id: 6ff9ea9a-9b83-4563-9d0a-87232d86ab2d
active_workspace_name: default
analytics_opt_in: true
store:
  backup_directory: /home/zaurall/projects/MLOpsProject/services/zenml/database_backup
  backup_strategy: in-memory
  database: /home/zaurall/projects/MLOpsProject/services/zenml/local_stores/default_zen_store/zenml.db
  driver: sqlite
  max_overflow: 20
  pool_pre_ping: true
  pool_size: 20
  secrets_store:
    type: sql
  ssl_verify_server_cert: false
  type: sql
  url: sqlite:////home/zaurall/projects/MLOpsProject/services/zenml/local_stores/default_zen_store/zenml.db
user_id: ae4f080d-c1c3-4775-afd6-c182a339d101
version: 0.58.2
