active_stack_id: 2a24e236-b0ae-4f95-9fa6-f496e682ada6
active_workspace_name: default
analytics_opt_in: true
store:
  api_token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2ZWFmZWUzOC1hNTIxLTQ1MzctODBhZS1jYmYxYzBkMDhhOGIiLCJpc3MiOiJhZTRmMDgwZC1jMWMzLTQ3NzUtYWZkNi1jMTgyYTMzOWQxMDEiLCJhdWQiOiJhZTRmMDgwZC1jMWMzLTQ3NzUtYWZkNi1jMTgyYTMzOWQxMDEifQ.gn793b4iJEJhJeKmh-f2njsGRm7vdcpHeNWokKbjqwY
  http_timeout: 30
  password: ''
  type: rest
  url: http://127.0.0.1:9000
  username: default
  verify_ssl: true
user_id: ae4f080d-c1c3-4775-afd6-c182a339d101
version: 0.58.2
