model_name: decision_tree_regression
artifact_path: basic_dtr

tag_key: "model"
tag_value: "basic DTR"

module_name: "sklearn.tree"
class_name: "DecisionTreeRegressor"

params:
  criterion: ['squared_error', 'absolute_error', 'poisson']
  splitter: ["best", "random"]
  max_depth: [10, 20, 30, 50, 100]
