model_name: linear_regression
artifact_path: basic_lr

tag_key: "model"
tag_value: "basic LR"

module_name: "sklearn.linear_model"
class_name: "LinearRegression"

params:
  fit_intercept: [True, False]
  n_jobs: [1, -1]


# hydra:
#   sweeper:
#     params:
#       +params.penalty: "'l1', 'l2'"
#       +params.solver: "'saga'"
#       +params.max_iter: "100, 200, 1000"
#       +params.random_state: 88
#       +params.C: range(start=0.1, stop=1, step=0.1)