# model_name: logistic_regression
# artifact_path: basic_lr

# tag_key: "model"
# tag_value: "basic LR"

# module_name: "sklearn.linear_model"
# class_name: "LogisticRegression"

# params:
#   solver: ["saga", "liblinear"] # , "lbfgs" ] 
#   max_iter: [1000, 2000, 5000]
#   random_state: [42]
#   C: [0.1, 0.5, 0.9]