model_name: ridge_regression
artifact_path: basic_ridge

tag_key: "model"
tag_value: "basic Ridge"

module_name: "sklearn.linear_model"
class_name: "Ridge"

params:
  alpha: [0.1, 1.0, 5.0, 10.0]
  fit_intercept: [True, False]
  solver: ['auto', 'svd', 'cholesky','sparse_cg']