defaults:
  - _self_

folds: 3

evaluation_metric: "neg_mean_squared_error"
cv_evaluation_metric: "mean_test_neg_mean_squared_error"

pyfunc_predict_fn: "predict"

metrics:
  mean_squared_error: "neg_mean_squared_error"
  mean_absolute_error: "neg_mean_absolute_error"
  r2_score: "r2"