defaults:
  - _self_

folds: 3
evaluation_metric: "neg_mean_squared_error"
cv_evaluation_metric: "mean_test_score"
pyfunc_predict_fn: "predict"

metrics:
  r2: "r2"
  mse: "neg_mean_squared_error"
  mae: "neg_mean_absolute_error"
