model_name: random_forest
artifact_path: basic_rf

tag_key: "model"
tag_value: "basic RF"

module_name: "sklearn.ensemble"
class_name: "RandomForestRegressor"

params:
  n_estimators: [100, 200, 500]
    max_depth: [3, 5, 10]
    min_samples_split: [2, 5, 10]
