defaults:
  - _self_

data_store: localstore
data_path: 'data/samples/sample.csv'

sample_size: 0.2
kaggle_url: brllrb/uber-and-lyft-dataset-boston-ma
# TODO
dataset_name: experiment.csv
output_name: sample.csv
day_of_week_column: 'day_of_week' 
datetime_column: 'datetime'
target_column: 'price'
categorical_columns:
  - 'source'
  - 'destination'
  - 'name'
  - 'short_summary'
numerical_columns:
  - 'hour'
  - 'month'
  - 'day_of_week'
  - 'day'
  - 'distance'
  - 'surge_multiplier'
  - 'apparentTemperature'
  - 'precipIntensity'
  - 'precipProbability'
  - 'humidity'
  - 'windSpeed'
  - 'visibility'
  - 'pressure'
  - 'windBearing'
  - 'cloudCover'
  - 'uvIndex'
  - 'precipIntensityMax'
date_columns:
  - 'hour'
  - 'month'
  - 'day_of_week'
  - 'day'