# .github/workflows/test-code.yaml

name: Validate model

on:
  push: 
    branches:
      - main

    paths:
      - 'src/**'
      - 'scripts/**'
      - 'services/airflow/dags/**'
      - 'tests/**'
      - 'configs/**'
      - '.github/**'
permissions:
  contents: read


jobs:
  validate-model:
    runs-on: ubuntu-latest 
    defaults: 
      run:
        shell: bash
        working-directory: .

    steps:
      - name: Checking out our code
        uses: actions/checkout@v4

      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11.0'
          cache: 'pip'
    
      - name: Install python packages
        run: |
            python3.11 -m pip install --upgrade pip 
            pip3.11 install -r cicd_requirements.txt --upgrade
        
      - name: Export variables
        run: | 
          echo $PWD
          echo "ZENML_CONFIG_PATH=$PWD/services/zenml" >> $GITHUB_ENV
          echo "PROJECTPATH=$PWD" >> $GITHUB_ENV
          echo "AIRFLOW_HOME=$PWD/services/airflow" >> $GITHUB_ENV
          echo "PYTHONPATH=$PWD/src" >> $GITHUB_ENV

      - name: Validate the model
        run: python3 src/validate.py model.challenger_model_aliases=['challenger']  '+sample_url="https://drive.google.com/uc?export=download&id=1_we1maZ7kgBsAr5dEUQ8VGSV6kXmyPFU"' 'test_data_version="v5"'
      


